language: node_js
node_js:
    - 'stable'
cache:
    directories:
        - node_modules
script:
    - npm test --watch
    - npm run build
deploy:
    provider: pages
    skip_cleanup: true
    on:
        branch: develop
